### ISSUE TITLE
Не получается настроить доступ к серверам Google на Fedora Linux

### ISSUE THREAD

**Issue by ReydAnD913** [krlvm/PowerTunnel#141]
Здравствуйте!
Недавно решил попробовать Fedora Linux. Т.к. у нас заблокированы Google сервера (Youtube в частности), то по привычке скачал и запустил PowerTunnel.jar
Появилось окно , сервер стартовал корректно, но вот сайты так и не открываются. При этом на Windows все работает корректно.
Помогите, пожалуйста разобраться, что не так в Linux. При старте самого приложения явных ошибок вроде не было (прикреплю ниже). По настройкам самого приложения также все идентично на обеих ОС.
Заранее огромное Спасибо!

Вот что было в терминале:
$ java -jar PowerTunnel.jar
PowerTunnel version 2.5.2
Powerful and extensible proxy server
(c) krlvm, 2019-2022

> Tray is not available: null
java.lang.UnsupportedOperationException
	at java.awt.TrayIcon.<init>(TrayIcon.java:144)
	at java.awt.TrayIcon.<init>(TrayIcon.java:168)
	at java.awt.TrayIcon.<init>(TrayIcon.java:197)
	at java.awt.TrayIcon.<init>(TrayIcon.java:227)
	at io.github.krlvm.powertunnel.desktop.managers.TrayManager.load(TrayManager.java:67)
	at io.github.krlvm.powertunnel.desktop.application.GraphicalApp.<init>(GraphicalApp.java:61)
	at io.github.krlvm.powertunnel.desktop.Main.main(Main.java:237)
00:00:06.955 [Thread-1] INFO  i.g.k.p.PowerTunnel - Registered plugin 'DNS' [dns] v1.0.2 (3) by krlvm
00:00:06.958 [Thread-1] INFO  i.g.k.p.PowerTunnel - Registered plugin 'LibertyTunnel' [libertytunnel] v1.0.7 (8) by krlvm
00:00:06.966 [Thread-1] INFO  i.g.k.p.p.l.LibertyTunnel - Loading local blacklist...
00:00:06.967 [Thread-1] INFO  i.g.k.p.p.l.LibertyTunnel - Loaded 0 blocked websites
00:00:06.969 [Thread-1] INFO  i.g.k.p.LittleProxyServer - Starting LittleProxy Server...
00:00:07.014 [Thread-1] INFO  o.l.p.i.DefaultHttpProxyServer - Starting proxy at address: /127.0.0.1:8085
00:00:07.029 [Thread-1] INFO  o.l.p.i.DefaultHttpProxyServer - Proxy listening with TCP transport
00:00:07.075 [Thread-1] INFO  o.l.p.i.DefaultHttpProxyServer - Proxy started at address: /127.0.0.1:8085
00:00:07.076 [Thread-1] INFO  i.g.k.p.LittleProxyServer - LittleProxy Server is listening at 127.0.0.1:8085
00:00:07.076 [Thread-1] INFO  i.g.k.p.d.a.DesktopApp - Serving at 127.0.0.1:8085

**Comment by krlvm** [comment]
Вы не забыли указать `127.0.0.1:8085` как системный прокси-сервер или указать его как прокси в браузере? Первое на Windows происходит автоматически.

**Comment by ReydAnD913** [comment]
> Вы не забыли указать `127.0.0.1:8085` как системный прокси-сервер или указать его как прокси в браузере? Первое на Windows происходит автоматически.
Не то, чтоб забыл ) Я даже не знал, что нужно еще что-то делать))) (Привык, что из под Виндовс все автоматом). Сейчас Вы подсказали, я нашел как это сделать, указал прокси, запустил програмку и все заработало )
Спасибо Вам огромнейшее!)
