### ISSUE TITLE
PAC файл не применяется автоматически

### ISSUE THREAD

**Issue by megapro17** [krlvm/PowerTunnel#44]
Сколько смотрел в коде так и не смог понять как его вручную ввести, по какому адресу

![Снимок экрана 2021-07-29 232918](https://user-images.githubusercontent.com/16743370/127561605-996200c4-4713-40c3-9361-f4c8d926653b.png)

**Comment by megapro17** [comment]
Или это не требуется? Проблема в том, что у меня в government-blacklist.txt всего один домен, а обходы применяются ко всем доменам и появляются непонятные ошибки
```
[i] CONNECT / functional.events.data.microsoft.com
 [+] Apply 'FAKE' SNI Trick: functional.events.data.microsoft.com
14200 [LittleProxy-0-ProxyToServerWorker-2] INFO org.littleshoot.proxy.impl.ProxyToServerConnection - (HANDSHAKING) [id: 0x8ecde9cf, L:0.0.0.0/0.0.0.0:56626 ! R:assets.msn.com/23.73.4.96:443]: Connection to upstream server failed
javax.net.ssl.SSLException: Received fatal alert: internal_error
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1647)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1615)
        at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1781)
        at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1070)
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:896)
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:766)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
        at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:295)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1330)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1225)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1272)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by megapro17** [comment]
Я не могу отредактировать wiki, допиши там что можно установить сертификат через командную строку от администратора на винде:
```
certutil -addstore "Root" powertunnel-root-ca.cer
certutil -delstore "Root" "PowerTunnel Root CA"
```

**Comment by krlvm** [comment]
Я указывал прямой путь к PAC файлу, только не помню как.

Модификация SNI действительно ломает большинство сайтов, в основном потому что ломает некоторые CDN. Проверьте список ещё раз, там должна отсутствовать строка со звёздочкой.

Я сам использую опцию "government blacklist mirror", указывая там адрес списка блокировок из скрипта обновления GoodbyeDPI/Antizapret: https://antizapret.prostovpn.org/domains-export.txt

**Comment by krlvm** [comment]
> Я не могу отредактировать wiki, допиши там что можно установить сертификат через командную строку от администратора на винде:
> 
> ```
> certutil -addstore "Root" powertunnel-root-ca.cer
> certutil -delstore "Root" "PowerTunnel Root CA"
> ```

Спасибо, какое-то время назад хотел поискать способ автоматической установки сертификата, но так и забыл об этом.

**Comment by megapro17** [comment]
> Модификация SNI действительно ломает большинство сайтов, в основном потому что ломает некоторые CDN. Проверьте список ещё раз, там должна отсутствовать строка со звёздочкой.

Да, отсутствует, тоже самое и с файлом txt, применяется на все сайты

**Comment by krlvm** [comment]
Проверил все еще раз:
1) Случайно не включен внешний прокси-сервер (`upstream proxy server`, третья опция сверху в интерфейсе настроек)?
2) Все работает корректно в последней версии ([v1.14](https://github.com/krlvm/PowerTunnel/releases/tag/v1.14)), до нажатия на кнопку "Reload" у меня была лишь звездочка в списке заблокированных ресурсов, после замены ее на конкретный список сайтов:
![Log](https://user-images.githubusercontent.com/51774833/127625126-08f98801-0581-4ece-94aa-938c0ba1d468.png)
Попробуйте все же вместо заполнения .txt файла прописать вот это, в таком случае файл склеится с этим списком (файл лучше очистить):
![image](https://user-images.githubusercontent.com/51774833/127625430-d764b82c-57b7-46ad-b4a3-fb7f8c6c09b8.png)
![image](https://user-images.githubusercontent.com/51774833/127625959-454b0361-91a0-4866-8dd0-c55eeffdf6a7.png)
3) Мне удалось выяснить основную причину по которой ломаются сайты, дело в том, что весь HTTPS трафик после MITM'а LittleProxy обрабатывает внутри как HTTP (как, например, скорее всего, казахские DPI после установки государственного Root CA), т.е. к трафику применяются вот эти настройки - из-за них и нарушается работа, их нужно отключить при включенной модификации SNI:
![image](https://user-images.githubusercontent.com/51774833/127626563-6145ddce-3343-49ad-b418-0b1dd56136f5.png)
Я добавил `yandex.ru` в список блокировок, установил сертификат и обнаружил, что мне не удается перейти по результату поиска из-за точки в конце домена:
![image](https://user-images.githubusercontent.com/51774833/127627161-cf6a2f0e-cf60-46c1-baa3-79861514f04d.png)
Если эту точку вручную убрать, то мне удается перейти по адресу - соотвественно, аналогичная проблема с большинством картинок, скриптов, стилей и прочих asset'ов. Такая проблема возникает в основном в Firefox.

Удалите все файлы в директории и попробуйте еще раз. Если не хотите переустанавливать сертификат, то не удаляйте файлы сертификата и скопируйте значение `powertunnel.cert.password` из файла настроек (`settings.ini`), а затем вставьте его в только что сгенерированный новый файл настроек.

**Comment by megapro17** [comment]
1. не включён
2. ввёл, никаких изменений, даже файл удалил.
3. самый прикол что я отключил все функции с самого начала, но сайты всё равно ломались.
4. сбросил настойки, добавил ссылку на домены, но всё тоже самое, трюки применяются ко всем сайтам. так как мне вручную добавить в системе ссылку на pac файл?
```
[#] Loading government blacklist from the mirror...
[#] Loaded '85983' government-blocked websites from the mirror
[i] Loaded '85984' government blocked sites, '0' user blocked sites, '0' user whitelisted sites
```
может ява какая-то не та?
```
openjdk version "1.8.0_242-release"
OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
```

**Comment by krlvm** [comment]
Я думаю, что это никак не связано с версией Java (у вас установлен OpenJDK), но я бы попробовал где-нибудь установить JRE с java.com. Что-то приводит к тому, что все сайты помечаются как заблокированные.

**Comment by krlvm** [comment]
Проверьте на [версии 2.0](https://github.com/krlvm/PowerTunnel/releases/tag/v2.0-rc)

**Comment by megapro17** [comment]
Хм, не могу понять. Сайты не ломаются, проверял с Shift+F5, но даже не у заблокированных сайтов другой сертификат. В настройках плагина адрес списка блокировки ввёл и всё отключил кроме подмены SNI. В главных настройках всё по умолчанию

**Comment by krlvm** [comment]
С такой конфигурацией все работает, проверил на Windows 11 и последней версии Chromium (Edge Canary), JRE с [java.com](https://java.com) (Update 301).
Для использования локального PAC-файла начинайте адрес с `file://`, например `file://C:/.../PowerTunnel/proxy.pac`
[PowerTunnel2.zip](https://github.com/krlvm/PowerTunnel/files/7013127/PowerTunnel2.zip)

![Снимок экрана 2021-08-19 125239](https://user-images.githubusercontent.com/51774833/130040986-31fc0776-ebc2-4fad-86a4-4ba54d2a5566.png)

**Comment by megapro17** [comment]
да, у меня тоже работает, но трюки всё равно применяются ко всем сайтам, судя по сертификату. А где вообще опция включения pac файла? 
![image](https://user-images.githubusercontent.com/16743370/130236928-d426f397-03e9-4cf4-931b-2dd139c67d8d.png)
![image](https://user-images.githubusercontent.com/16743370/130236986-fc841b3f-94d9-4f7d-b4fd-9c46e21b17c6.png)
![image](https://user-images.githubusercontent.com/16743370/130236996-0d62b7d8-29ce-4841-8ef6-95bdeeb3bfae.png)

**Comment by krlvm** [comment]
На момент релиза версии 2.0-rc я забыл добавить API для выборочного применения MITM, поэтому модификация SNI применялась ко всем сайтам (хотя в 1.14 такой проблемы нет). Генерация PAC поддерживается в последней версии LibertyTunnel.

Ниже предварительная версия с исправлением SNI и поддержкой PAC, `LibertyTunnel.jar` нужно переместить `plugins`.
[PowerTunnel-v2.0-rc-u1.zip](https://github.com/krlvm/PowerTunnel/files/7023515/PowerTunnel-v2.0-rc-u1.zip)
