### ISSUE TITLE
Failed to open plugins references

### ISSUE THREAD

**Issue by dickyharper** [krlvm/PowerTunnel#81]
Get this error when trying to open LibertyTunnel and DNS Plugins settings
Powertunnel 2.0 
JDK : 17.0.1
JRE : (build 1.8.0_311-b11)
![javaw_oxFjqLpKXF](https://user-images.githubusercontent.com/50758669/147577998-85d08a49-2381-4f44-b718-b71b755ed900.png)

**Comment by krlvm** [comment]
Looks like the configuration files are damaged, can you try to delete them?

**Comment by dickyharper** [comment]
> Looks like the configuration files are damaged, can you try to delete them?

Just in case I deleted the Powertunnel.jar file and downloaded it again. The result is still the same.
[hs_err_pid1624.log](https://github.com/krlvm/PowerTunnel/files/7785622/hs_err_pid1624.log)

**Comment by krlvm** [comment]
Which plugin's preferences you are trying to edit?

**Comment by krlvm** [comment]
This is very strange, because this error pops up when preference type cannot be found in enum, which I guarantee exists. Check your encoding.

**Comment by dickyharper** [comment]
> Which plugin's preferences you are trying to edit?



> This is very strange, because this error pops up when preference type cannot be found in enum, which I guarantee exists. Check your encoding.

I wanted to change dns resolver preferences. Enabling Doh settings. But I didn't change anything because it won't turn on. The sizes of dns.ini and libertytunnel.ini are 0kb, they are empty. Besides, powertunnel works without any problems.

**Comment by krlvm** [comment]
Can you check PowerTunnel logs? To see the output, launch it in console mode using `java -jar PowerTunnel.jar`

Try to download Microsoft's build of OpenJDK: https://www.microsoft.com/openjdk

![image](https://user-images.githubusercontent.com/51774833/147589597-78943b16-db48-49d2-b4c8-9777a4f01a7f.png)

**Comment by dickyharper** [comment]
I installed microsoft openjdk. I restarted the pc. I ran it as you said.
![cmd_2OKAAfs10u](https://user-images.githubusercontent.com/50758669/147595052-cd1dec64-6698-4c8e-ad3a-c6e116466ed0.png)
![cmd_X0ZarBSuzY](https://user-images.githubusercontent.com/50758669/147595062-1ad40711-5883-40ee-bed4-7ed39a994e79.png)

**Comment by krlvm** [comment]
The log seems to be OK, try to launch PowerTunnel with UTF-8 encoding: `java -Dfile.encoding=UTF8 -jar PowerTunnel.jar`

**Comment by dickyharper** [comment]
> The log seems to be OK, try to launch PowerTunnel with UTF-8 encoding: `java -Dfile.encoding=UTF8 -jar PowerTunnel.jar`
Still same
`WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
21:29:48.733 [main] ERROR i.g.k.p.d.u.UIUtility - Failed to set AWT app name: awtAppClassName
java.lang.NoSuchFieldException: awtAppClassName
        at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
        at io.github.krlvm.powertunnel.desktop.utilities.UIUtility.setAWTName(UIUtility.java:94) [PowerTunnel.jar:?]
        at io.github.krlvm.powertunnel.desktop.Main.main(Main.java:213) [PowerTunnel.jar:?]
Locale 'tr' is not supported
io.github.krlvm.powertunnel.exceptions.PreferenceParseException: Unsupported preference type: 'string"
        at io.github.krlvm.powertunnel.preferences.PreferenceParser.parsePreference(PreferenceParser.java:90)
        at io.github.krlvm.powertunnel.preferences.PreferenceParser.parsePreferences(PreferenceParser.java:62)
        at io.github.krlvm.powertunnel.desktop.frames.PluginsFrame.openPreferences(PluginsFrame.java:281)
        at io.github.krlvm.powertunnel.desktop.frames.PluginsFrame.lambda$null$8(PluginsFrame.java:242)
        at io.github.krlvm.powertunnel.desktop.frames.PluginsFrame.lambda$getJarLocaleBundleInputStream$10(PluginsFrame.java:260)
        at io.github.krlvm.powertunnel.utilities.JarLoader.open(JarLoader.java:49)
        at io.github.krlvm.powertunnel.desktop.frames.PluginsFrame.getJarLocaleBundleInputStream(PluginsFrame.java:256)
        at io.github.krlvm.powertunnel.desktop.frames.PluginsFrame.lambda$openPreferences$9(PluginsFrame.java:225)
        at io.github.krlvm.powertunnel.utilities.JarLoader.open(JarLoader.java:49)
        at io.github.krlvm.powertunnel.desktop.frames.PluginsFrame.openPreferences(PluginsFrame.java:220)
        at io.github.krlvm.powertunnel.desktop.frames.PluginsFrame.withSelectedValue(PluginsFrame.java:186)
        at io.github.krlvm.powertunnel.desktop.frames.PluginsFrame.lambda$new$5(PluginsFrame.java:97)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
        at java.desktop/java.awt.Component.processEvent(Component.java:6391)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalArgumentException: No enum constant io.github.krlvm.powertunnel.preferences.PreferenceType.STRİNG
        at java.base/java.lang.Enum.valueOf(Enum.java:273)
        at io.github.krlvm.powertunnel.preferences.PreferenceType.valueOf(PreferenceType.java:20)
        at io.github.krlvm.powertunnel.preferences.PreferenceParser.parsePreference(PreferenceParser.java:88)
        ... 46 more`

**Comment by krlvm** [comment]
Can't reproduce even with Turkish locale.
You can use [version 1.14](https://github.com/krlvm/PowerTunnel/releases/tag/v1.14) until I found the cause of the issue
