### ISSUE TITLE
Incompatibility with JDK >= 18

### ISSUE THREAD

**Issue by hardwarecrypto** [krlvm/PowerTunnel#87]
# java -jar PowerTunnel.jar -start
PowerTunnel version 2.0.1
Powerful and extensible proxy server
(c) krlvm, 2019-2022

WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make field private static java.lang.String sun.awt.X11.XToolkit.awtAppClassName accessible: module java.desktop does not "opens sun.awt.X11" to unnamed module @5c663359
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at io.github.krlvm.powertunnel.desktop.utilities.UIUtility.setAWTName(UIUtility.java:95)
        at io.github.krlvm.powertunnel.desktop.Main.main(Main.java:213)

**Comment by krlvm** [comment]
I'm aware of this error, actually this is a warning which does not impact application reliability, I disabled it in the upcoming release though.

**Comment by hardwarecrypto** [comment]
PowerTunnel version 2.0-rc3  - it is working version for (openjdk18)

**Comment by krlvm** [comment]
Well, I need to admit I did not test it throughly on JDK > 8, it even looks worse (maybe because of poorly impemented Java native DPI scaling).

![jdk8-jdk16](https://user-images.githubusercontent.com/51774833/152208681-52afc8c8-890e-4b6b-a889-817fa799e42a.png)

The reason of the crash is the workaround for #13, which no longer works in recent JDK versions.
This build should fix the issue, can you confirm?

[desktop-2.0.1-all.zip](https://github.com/krlvm/PowerTunnel/files/7988925/desktop-2.0.1-all.zip)

**Comment by hardwarecrypto** [comment]
> 
> The reason of the crash is the workaround for #13, which no longer works in recent JDK versions. This build should fix the issue, can you confirm?
> 
> [desktop-2.0.1-all.zip](https://github.com/krlvm/PowerTunnel/files/7988925/desktop-2.0.1-all.zip)

Yes, the app starts, but pages do not open in the browser:

_Connection to upstream server failed
io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
        at io.netty.handler.ssl.SslHandler$5.run(SslHandler.java:2060) [desktop-2.0.1-all.jar:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [desktop-2.0.1-all.jar:?]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) [desktop-2.0.1-all.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [desktop-2.0.1-all.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [desktop-2.0.1-all.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [desktop-2.0.1-all.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [desktop-2.0.1-all.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [desktop-2.0.1-all.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[SSLEngine] SSLEngineImpl_

**Comment by krlvm** [comment]
I don't think it may be related to the JRE/JDK version, are you trying to access a banned website?

**Comment by hardwarecrypto** [comment]
> are you trying to access a banned website?
Oh sure :)

**Comment by krlvm** [comment]
Are you using a blacklist with LibertyTunnel? Try to reset entire PowerTunnel configuration, i.e. clean the directory all but the jar file - I did not changed anything related to censorship bypass since the first preview of version 2.0.

**Comment by hardwarecrypto** [comment]
> Are you using a blacklist with LibertyTunnel? Try to reset entire PowerTunnel configuration, i.e. clean the directory all but the jar file - I did not changed anything related to censorship bypass since the first preview of version 2.0.

"Are you using a blacklist with LibertyTunnel?" - no.
I run everything in its clean form, without settings, and was delete all files except jar file.
But only works - "Version 2.0-rc3", and older versions.

**Comment by hardwarecrypto** [comment]
> Seems strange to me, [here's](https://github.com/krlvm/PowerTunnel/compare/v2.0-rc3...v2.0-rc4) the complete list of changes from rc3 to rc4 - there were only cosmetic changes.
> Does this happen with older JDK/JRE versions?

On JDK11 version everything works, on other versions, except for 18 did not check.

**Comment by krlvm** [comment]
I don't know why are you using JDK 18, because it will be released only in March - current builds may be unstable.

**Comment by hardwarecrypto** [comment]
> java -jar PowerTunnel.jar -start

same problem with openjdk 17.0.1

**Comment by krlvm** [comment]
Can't reproduce with [Microsoft's OpenJDK](https://www.microsoft.com/openjdk)
```
openjdk 17.0.1 2021-10-19 LTS
OpenJDK Runtime Environment Microsoft-28056 (build 17.0.1+12-LTS)
OpenJDK 64-Bit Server VM Microsoft-28056 (build 17.0.1+12-LTS, mixed mode, sharing)
```
